# Generated by Django 6.1.1 on 2026-10-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_initial_content_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم التنسيق")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="الافتراضي للغة"),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=dict, verbose_name="الخيارات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_formats",
                        to="core.language",
                        verbose_name="اللغة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنسيق تصدير",
                "verbose_name_plural": "تنسيقات التصدير",
                "ordering": ["language__name", "-is_default", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language", "name"),
                        name="unique_export_format_name_per_language",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("language",),
                        name="unique_default_export_format_per_language",
                    ),
                ],
            },
        ),
    ]
