# Generated by Django 6.1.1 on 2026-10-05 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0003_glossarytranslation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار البدء"),
                            ("running", "قيد التدقيق"),
                            ("done", "مكتمل"),
                            ("partial", "مكتمل جزئياً"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "language",
                    models.CharField(max_length=100, verbose_name="اللغة كما تُذكر في البرومت"),
                ),
                (
                    "arabic_script",
                    models.BooleanField(default=False, verbose_name="تُكتب بالحرف العربي"),
                ),
                (
                    "model",
                    models.CharField(max_length=100, verbose_name="نموذج Gemini"),
                ),
                (
                    "group_size",
                    models.PositiveSmallIntegerField(verbose_name="صفوف لكل طلب"),
                ),
                (
                    "prompt_version",
                    models.PositiveSmallIntegerField(verbose_name="نسخة البرومت"),
                ),
                ("prompt_snapshot", models.TextField(verbose_name="لقطة البرومت")),
                (
                    "request_config",
                    models.JSONField(blank=True, default=dict, verbose_name="إعدادات الطلب"),
                ),
                (
                    "extra_rules",
                    models.TextField(blank=True, verbose_name="قواعد إضافية"),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0, verbose_name="إجمالي الصفوف"),
                ),
                (
                    "eligible_rows",
                    models.PositiveIntegerField(default=0, verbose_name="الصفوف المؤهلة للنموذج"),
                ),
                (
                    "finding_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الملاحظات"),
                ),
                (
                    "prompt_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="توكن الإدخال"),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="توكن الإخراج"),
                ),
                (
                    "progress",
                    models.JSONField(blank=True, default=dict, verbose_name="التقدّم"),
                ),
                (
                    "stats",
                    models.JSONField(blank=True, default=dict, verbose_name="الإحصائيات"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الانتهاء"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طلبه",
                    ),
                ),
                (
                    "document_translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="content.documenttranslation",
                        verbose_name="ترجمة المستند",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة تدقيق",
                "verbose_name_plural": "مهام التدقيق",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, verbose_name="المفتاح")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "معلّقة"),
                            ("done", "منجزة"),
                            ("failed", "فاشلة"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="المحاولات"),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="آخر خطأ")),
                (
                    "raw_response",
                    models.TextField(blank=True, verbose_name="الرد الخام"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="بدء آخر محاولة"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاريخ الإنجاز"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="audit.auditjob",
                        verbose_name="المهمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مجموعة تدقيق",
                "verbose_name_plural": "مجموعات التدقيق",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AuditRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(verbose_name="الترتيب (id في البرومت)"),
                ),
                ("source_text", models.TextField(verbose_name="النص الأصلي")),
                ("target_text", models.TextField(blank=True, verbose_name="الترجمة")),
                (
                    "row_type",
                    models.CharField(
                        choices=[("translation", "ترجمة معنى"), ("naqhara", "نقحرة")],
                        default="translation",
                        max_length=12,
                        verbose_name="نوع الصف",
                    ),
                ),
                (
                    "hints",
                    models.JSONField(blank=True, default=list, verbose_name="تنبيهات آلية"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "لم يُفحص بعد"),
                            ("done", "تم"),
                            ("failed", "فشل الفحص"),
                            ("skipped", "مستبعد"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="حالة الفحص",
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(blank=True, max_length=255, verbose_name="سبب الاستبعاد"),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("مقبول", "مقبول"),
                            ("يحتاج مراجعة", "يحتاج مراجعة"),
                            ("مرفوض", "مرفوض"),
                        ],
                        max_length=30,
                        verbose_name="الحكم",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="ملخص المراجعة")),
                (
                    "error_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="عدد الأخطاء"),
                ),
                (
                    "max_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("حرج", "حرج"),
                            ("كبير", "كبير"),
                            ("متوسط", "متوسط"),
                            ("بسيط", "بسيط"),
                        ],
                        max_length=20,
                        verbose_name="أعلى خطورة",
                    ),
                ),
                (
                    "sharia_sensitive",
                    models.BooleanField(default=False, verbose_name="حساسية شرعية"),
                ),
                (
                    "needs_human_review",
                    models.BooleanField(default=False, verbose_name="يحتاج مراجعة بشرية"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rows",
                        to="audit.auditgroup",
                        verbose_name="المجموعة",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="audit.auditjob",
                        verbose_name="المهمة",
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_rows",
                        to="content.phrase",
                        verbose_name="الجملة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صف تدقيق",
                "verbose_name_plural": "صفوف التدقيق",
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="AuditFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveSmallIntegerField(default=1, verbose_name="الترتيب"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("rule", "قاعدة آلية"), ("model", "النموذج")],
                        default="model",
                        max_length=10,
                        verbose_name="مصدر الكشف",
                    ),
                ),
                (
                    "category_code",
                    models.CharField(blank=True, max_length=10, verbose_name="رمز الفئة"),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=100, verbose_name="الفئة"),
                ),
                (
                    "type_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="رمز النوع",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(blank=True, max_length=150, verbose_name="نوع الخطأ"),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("حرج", "حرج"),
                            ("كبير", "كبير"),
                            ("متوسط", "متوسط"),
                            ("بسيط", "بسيط"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="الخطورة",
                    ),
                ),
                (
                    "sharia_sensitive",
                    models.BooleanField(default=False, verbose_name="حساسية شرعية"),
                ),
                (
                    "detection",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("قطعي", "قطعي"),
                            ("استدلالي", "استدلالي"),
                            ("مؤشر اشتباه", "مؤشر اشتباه"),
                        ],
                        max_length=30,
                        verbose_name="طريقة الكشف",
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="الثقة %"),
                ),
                ("location", models.TextField(blank=True, verbose_name="موضع الخطأ")),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="شرح المشكلة"),
                ),
                (
                    "required_action",
                    models.TextField(blank=True, verbose_name="المطلوب"),
                ),
                (
                    "suggested_fix",
                    models.TextField(blank=True, verbose_name="التصحيح المقترح"),
                ),
                (
                    "needs_human_review",
                    models.BooleanField(default=False, verbose_name="يحتاج مراجعة بشرية"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="audit.auditjob",
                        verbose_name="المهمة",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="audit.auditrow",
                        verbose_name="الصف",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة تدقيق",
                "verbose_name_plural": "ملاحظات التدقيق",
                "ordering": ["row__seq", "seq"],
            },
        ),
        migrations.AddConstraint(
            model_name="auditgroup",
            constraint=models.UniqueConstraint(
                fields=("job", "key"), name="unique_audit_group_key_per_job"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditrow",
            constraint=models.UniqueConstraint(
                fields=("job", "seq"), name="unique_audit_row_seq_per_job"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditrow",
            constraint=models.UniqueConstraint(
                fields=("job", "phrase"), name="unique_audit_row_phrase_per_job"
            ),
        ),
    ]
