# Generated by Django 6.1.1 on 2026-10-05 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0003_glossarytranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "في الانتظار"),
                            ("running", "جارٍ"),
                            ("done", "اكتمل"),
                            ("failed", "فشل"),
                        ],
                        default="queued",
                        max_length=8,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "stage",
                    models.CharField(blank=True, max_length=120, verbose_name="المرحلة الجارية"),
                ),
                ("pct", models.PositiveSmallIntegerField(default=0, verbose_name="النسبة")),
                ("title", models.CharField(max_length=255, verbose_name="العنوان المطلوب")),
                (
                    "source_file_name",
                    models.CharField(blank=True, max_length=255, verbose_name="اسم الملف الأصلي"),
                ),
                ("result", models.JSONField(blank=True, null=True, verbose_name="نتيجة الواجهة")),
                ("error", models.TextField(blank=True, verbose_name="الخطأ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تحديث")),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.document",
                        verbose_name="المستند",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة تقطيع",
                "verbose_name_plural": "مهام التقطيع",
            },
        ),
    ]
